### ISSUE TITLE
SyntaxError: Invalid Syntax On Windows 10 Py3

### ISSUE THREAD

**Issue by secbug** [Microsoft/Cognitive-Face-Python#65]
Following the regular instructions in the read me on Win10 using Py3, it fails running "python sample" or "python3 sample" 

```
$ python sample
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\runpy. py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\runpy. py", line 85, in _run_code                                                           
    exec(code, run_globals)
  File "sample\__main__.py", line 8, in
    from view import MyApp
  File "sample\view\__init__.py", line 15, in
    from view.panel_detection import DetectionPanel
  File "sample\view\panel_detection.py", line 90
    @util.async

SyntaxError: invalid syntax
```

**Comment by acured** [comment]
Hi @secbug , can you have a try with python x64?

**Comment by acured** [comment]
Right, Both of these are used to define the function as async. "@util.async" is just an easier way of saying async_detect = util.async(async_detect).
