### ISSUE TITLE
 The length of faceIds is not in a valid range.

### ISSUE THREAD

**Issue by tusharacc** [microsoft/Cognitive-Face-Python#80]
I am using the identify operation to identify the face in persongroup. I have a person group with three images of same person. I am using the detect_with_stream to detect the face of test image. The operation - face_client.face.identify(face_ids, PERSON_GROUP_ID) is failing for me.

Code Snippet - 

    `
    image_bytes = base64.b64decode(base64Str.split(',')[1])
    face_ids = []
    # We use detection model 3 to get better performance.
    faces = face_client.face.detect_with_stream(io.BytesIO(image_bytes), detection_model='detection_03')
    for face in faces:
        face_ids.append(face.face_id)
    
    print ('Length of face id', face_ids)

    # Identify faces
    results = face_client.face.identify(face_ids, PERSON_GROUP_ID)
    print (results)
    `
base64Str - is the base64 string coming from the web application. Please note, that this code was working fine and i was able to identify the faces and also tested for negative scenario. Its just stopped working and I cant figure out why.

Python Console output - 

`Length of face id []
ERROR:main:Exception on /login [POST]
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 2447, 
in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1952, 
in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask_cors\extension.py", 
line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1821, 
in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1950, 
in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files (x86)\python36-32\lib\site-packages\flask\app.py", line 1936, 
in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\T9SAU2\OneDrive - Chubb\Documents\AngularJs\dashboard\backend\main.py", line 98, in login
    result = iden.convert_to_image(body['base64'])
  File "C:\Users\T9SAU2\OneDrive - Chubb\Documents\AngularJs\dashboard\backend\identify_users.py", line 48, in convert_to_image
    results = face_client.face.identify(face_ids, PERSON_GROUP_ID)
  File "c:\program files (x86)\python36-32\lib\site-packages\azure\cognitiveservices\vision\face\operations\_face_operations.py", line 313, in identify
    raise models.APIErrorException(self._deserialize, response)
azure.cognitiveservices.vision.face.models._models_py3.APIErrorException: (BadArgument) The length of faceIds is not in a valid range.
INFO:werkzeug:127.0.0.1 - - [21/Feb/2021 10:44:58] "POST /login HTTP/1.1" `

**Comment by tusharacc** [comment]
Please ignore the issue. The Canvas sized changed inadvertently and hence the image didnt have any face. I have corrected the canvas size and issue was resolved.
